### ISSUE TITLE
Haven - Releasing in 2020, links to unrelated games in ITAD

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1639] opened 2021-07-26 21:01 UTC
Here is the game page on Steam: https://store.steampowered.com/app/983970/Haven/

https://isthereanydeal.com/game/haven/info/

Links to games with the same name in itch.io and Indiegala, but the picture is of the Steam unreleased game.

[Issue created by [deleted]: 2020-02-04]

**Comment by MarkitkaM** [comment] 2021-09-05 08:40
Probably duplicate of #1926.

Pictures are the same, the game was already released 3rd december 2020

Itch.io is not tracked anymore via duplicated task above.

**Closed** 2021-09-05 08:41 UTC
Labels: bug, duplicate, game, entry
