### ISSUE TITLE
Magicka 2 is not saled at GreenManGaming for Russia

### ISSUE THREAD

**Issue by tfedor** [IsThereAnyDeal/IsThereAnyDeal-Issues#1890] opened 2021-07-27 19:24 UTC
> ---------- Forwarded message ---------  
> From: CallumGMG \(Green Man Gaming Support\)  
> Date: Wed, 25 Nov 2020 at 19:12  
> Subject: \[Green Man Gaming Support\] We've updated your Ticket!
>
> Thank you for getting in touch with us.  
> Unfortunately, the game in your shopping cart is currently unavailable for purchase due to regional restrictions, and I'm afraid we do not have information on when it will be available again.  
> We apologise for any inconvenience caused by this process.
>
> Kind regards,  
> Carlos  
> Customer Support  
> Green Man Gaming

‌

[Issue created by Bujno: 2020-11-25]

**Comment by MarkitkaM** [comment] 2021-09-06 05:55
I am closing this issue based on the e-mail from Green Gaming Man.

**Closed by MarkitkaM** 2021-09-06 05:55 UTC
Labels: game, region

**Comment by Korb** [comment] 2021-09-06 06:35
> I am closing this issue

@MarkitkaM, what decision was made?

**Comment by MarkitkaM** [comment] 2021-09-07 07:08
GMG is not showing any region restriction. So we are not able to do anything with that.
We apologize for any inconvenience caused by this.
